[build]
target = "index.html"
dist = "../frontend"

#[clean]
#dist = true

[serve]
address = "127.0.0.1"
port = 8080
rewrite_backend = "http://127.0.0.1:3000"

[[proxy]]
path = "/api"
backend = "http://127.0.0.1:3000/api"
